### ISSUE TITLE
APIKEy missing - Build Fail Error

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-tekton-resources#10]
╷
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "ingress_subdomain" but a
│ value was found in file "terraform.tfvars". If you meant to use this value,
│ add a "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
╷
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "vpc_subnet_count" but a
│ value was found in file "terraform.tfvars". If you meant to use this value,
│ add a "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
╷
│ Error: ibmcloud_api_key or bluemix_api_key or iam_token and iam_refresh_token must be provided. Please see the documentation on how to configure it
│ 
│   with module.resource_group.data.ibm_resource_group.resource_group,
│   on .terraform/modules/resource_group/main.tf line 53, in data "ibm_resource_group" "resource_group":
│   53: data ibm_resource_group resource_group {

https://github.com/cloud-native-toolkit/terraform-gitops-tekton-resources/runs/6341486531?check_suite_focus=true

**Comment by balasgit** [comment]
@seansund 

Reviewed the RG module **(https://github.com/cloud-native-toolkit/terraform-ibm-resource-group/blob/main/main.tf)** which expects the API_Key. I am setting the APIKEy in the stage1-RG.tf like this but the Terraform RG module complains the APIKey missing. 

**Current Module Stage1-Resource-group.tf**

module "resource_group" {
  source = "github.com/cloud-native-toolkit/terraform-ibm-resource-group.git"

  resource_group_name = var.resource_group_name
  **ibmcloud_api_key    = var.ibmcloud_api_key**

}

**Debugging Ideas** 

1. How do i validate this module passing APIKEY from stage1-RG.tf to terraform-resource-group ? 
  - I am thinking to add print out on the terraform-Resource-group main.tf  (Line 25) as shown below but i want to check with you for better ideas

**Any other thoughts to debug this issue**

terraform-RG Module Main.tf (RG module (https://github.com/cloud-native-toolkit/terraform-ibm-resource-group/blob/main/main.tf)

![Screen Shot 2022-05-10 at 6 36 24 PM](https://user-images.githubusercontent.com/25986944/167741479-33b711a6-b86c-406d-b838-a7eed402d024.png)

**Comment by triceam** [comment]
@balasgit you need a provider block in your test/stages folder.  see https://github.com/cloud-native-toolkit/terraform-ibm-resource-group/blob/main/test/stages/provider.tf
